name: 2021-image-super-resolution
dependencies:
    - python
    - bs4
    - requests
    - io
    - zipfile
    - urllib.request
    - re
    - os
    - tensorflow
    - pip
    - pip:
        -
        -